/*
 * Copyright (C) 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Autogenerated from camera metadata definitions in
 * /system/media/camera/docs/metadata_definitions.xml
 * *** DO NOT EDIT BY HAND ***
 */

package android.hardware.camera.metadata;

/**
 * android.automotive.lens.facing enumeration values
 * @see ANDROID_AUTOMOTIVE_LENS_FACING
 * See system/media/camera/docs/metadata_definitions.xml for details.
 */
@VintfStability
@Backing(type="int")
enum AutomotiveLensFacing {
    ANDROID_AUTOMOTIVE_LENS_FACING_EXTERIOR_OTHER,
    ANDROID_AUTOMOTIVE_LENS_FACING_EXTERIOR_FRONT,
    ANDROID_AUTOMOTIVE_LENS_FACING_EXTERIOR_REAR,
    ANDROID_AUTOMOTIVE_LENS_FACING_EXTERIOR_LEFT,
    ANDROID_AUTOMOTIVE_LENS_FACING_EXTERIOR_RIGHT,
    ANDROID_AUTOMOTIVE_LENS_FACING_INTERIOR_OTHER,
    ANDROID_AUTOMOTIVE_LENS_FACING_INTERIOR_SEAT_ROW_1_LEFT,
    ANDROID_AUTOMOTIVE_LENS_FACING_INTERIOR_SEAT_ROW_1_CENTER,
    ANDROID_AUTOMOTIVE_LENS_FACING_INTERIOR_SEAT_ROW_1_RIGHT,
    ANDROID_AUTOMOTIVE_LENS_FACING_INTERIOR_SEAT_ROW_2_LEFT,
    ANDROID_AUTOMOTIVE_LENS_FACING_INTERIOR_SEAT_ROW_2_CENTER,
    ANDROID_AUTOMOTIVE_LENS_FACING_INTERIOR_SEAT_ROW_2_RIGHT,
    ANDROID_AUTOMOTIVE_LENS_FACING_INTERIOR_SEAT_ROW_3_LEFT,
    ANDROID_AUTOMOTIVE_LENS_FACING_INTERIOR_SEAT_ROW_3_CENTER,
    ANDROID_AUTOMOTIVE_LENS_FACING_INTERIOR_SEAT_ROW_3_RIGHT,
}
