/*
 * Copyright (C) 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Autogenerated from camera metadata definitions in
 * /system/media/camera/docs/metadata_definitions.xml
 * *** DO NOT EDIT BY HAND ***
 */

package android.hardware.camera.metadata;

/**
 * android.scaler.availableFormats enumeration values
 * @see ANDROID_SCALER_AVAILABLE_FORMATS
 * See system/media/camera/docs/metadata_definitions.xml for details.
 */
@VintfStability
@Backing(type="int")
enum ScalerAvailableFormats {
    ANDROID_SCALER_AVAILABLE_FORMATS_RAW16 = 0x20,
    ANDROID_SCALER_AVAILABLE_FORMATS_RAW_OPAQUE = 0x24,
    ANDROID_SCALER_AVAILABLE_FORMATS_YV12 = 0x32315659,
    ANDROID_SCALER_AVAILABLE_FORMATS_YCrCb_420_SP = 0x11,
    ANDROID_SCALER_AVAILABLE_FORMATS_IMPLEMENTATION_DEFINED = 0x22,
    ANDROID_SCALER_AVAILABLE_FORMATS_YCbCr_420_888 = 0x23,
    ANDROID_SCALER_AVAILABLE_FORMATS_BLOB = 0x21,
    ANDROID_SCALER_AVAILABLE_FORMATS_RAW10 = 0x25,
    ANDROID_SCALER_AVAILABLE_FORMATS_RAW12 = 0x26,
    ANDROID_SCALER_AVAILABLE_FORMATS_Y8 = 0x20203859,
}
