/*
 * Copyright (C) 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *//*
 * Autogenerated from camera metadata definitions in
 * /system/media/camera/docs/metadata_definitions.xml
 * *** DO NOT EDIT BY HAND ***
 */
///////////////////////////////////////////////////////////////////////////////
// THIS FILE IS IMMUTABLE. DO NOT EDIT IN ANY CASE.                          //
///////////////////////////////////////////////////////////////////////////////

// This file is a snapshot of an AIDL file. Do not edit it manually. There are
// two cases:
// 1). this is a frozen version file - do not edit this in any case.
// 2). this is a 'current' file. If you make a backwards compatible change to
//     the interface (from the latest frozen version), the build system will
//     prompt you to update this file with `m <name>-update-api`.
//
// You must not make a backward incompatible change to any AIDL file built
// with the aidl_interface module type with versions property set. The module
// type is used to build AIDL files in a way that they can be used across
// independently updatable components of the system. If a device is shipped
// with such a backward incompatible change, it has a high risk of breaking
// later when a module using the interface is updated, e.g., Mainline modules.

package android.hardware.camera.metadata;
@Backing(type="int") @VintfStability
enum SensorReferenceIlluminant1 {
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_DAYLIGHT = 1,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_FLUORESCENT = 2,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_TUNGSTEN = 3,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_FLASH = 4,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_FINE_WEATHER = 9,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_CLOUDY_WEATHER = 10,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_SHADE = 11,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_DAYLIGHT_FLUORESCENT = 12,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_DAY_WHITE_FLUORESCENT = 13,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_COOL_WHITE_FLUORESCENT = 14,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_WHITE_FLUORESCENT = 15,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_STANDARD_A = 17,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_STANDARD_B = 18,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_STANDARD_C = 19,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_D55 = 20,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_D65 = 21,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_D75 = 22,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_D50 = 23,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_ISO_STUDIO_TUNGSTEN = 24,
}
