; Version 1, introduced in Android 12:
DeviceInfo = {
    ? "brand" : tstr,
    ? "manufacturer" : tstr,
    ? "product" : tstr,
    ? "model" : tstr,
    ? "board" : tstr,
    ? "vb_state" : "green" / "yellow" / "orange",  ; Taken from the AVB values
    ? "bootloader_state" : "locked" / "unlocked",  ; Taken from the AVB values
    ? "vbmeta_digest": bstr,                       ; Taken from the AVB values
    ? "os_version" : tstr,                         ; Same as
                                                   ; android.os.Build.VERSION.release
    ? "system_patch_level" : uint,     ; YYYYMM, must match KeyMint OS_PATCHLEVEL
    ? "boot_patch_level" : uint,       ; YYYYMMDD, must match KeyMint BOOT_PATCHLEVEL
    ? "vendor_patch_level" : uint,     ; YYYYMMDD, must match KeyMint VENDOR_PATCHLEVEL
    "version" : 1,                                 ; The CDDL schema version.
    "security_level" : "tee" / "strongbox"
    "att_id_state": "locked" / "open",  ; Attestation IDs State. If "locked", this
                                        ; indicates a device's attestable IDs are
                                        ; factory-locked and immutable. If "open",
                                        ; this indicates the device is still in a
                                        ; provisionable state and the attestable IDs
                                        ; are not yet frozen.
}
