;
; Copyright (C) 2023 The Android Open Source Project
;
; Licensed under the Apache License, Version 2.0 (the "License");
; you may not use this file except in compliance with the License.
; You may obtain a copy of the License at
;
;      http://www.apache.org/licenses/LICENSE-2.0
;
; Unless required by applicable law or agreed to in writing, software
; distributed under the License is distributed on an "AS IS" BASIS,
; WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
; See the License for the specific language governing permissions and
; limitations under the License.
;

; P-256 public key for key exchange.
PlainPubKey = [ ; COSE_Key [RFC9052 s7]
    1 : 2,                       ; Key type : EC2
    3 : -27,                     ; Algorithm : ECDH-SS + HKDF-256
    -1 : 1,                      ; Curve: P256
    -2 : bstr,                   ; X coordinate, big-endian
    -3 : bstr                    ; Y coordinate, big-endian
]
